spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:root}
      database: chat
      authentication-database: admin
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  port: 9090
