spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:root}
      database: chat
      authentication-database: admin
  server:
    secretKey: ${SECRET_KEY:"614E645267556B58703272357538782F413F4428472B4B6250655368566D5971"}
